name: TVBox 接口自动化私有化

on:
  schedule:
    - cron: '0 21 * * *' # 每天北京时间凌晨 5 点运行
  workflow_dispatch:      # 支持点击按钮手动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 检出 ol 仓库
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MY_USERNAME }}/ol
          path: ol  # 必须拉取到名为 ol 的文件夹
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          persist-credentials: true

      - name: 2. 修复 git 权限 (Actions 必做)
        run: git config --global --add safe.directory /home/runner/work/${{ github.event.repository.name }}/ol

      - name: 3. 运行 Docker 并挂载已有的 ol 文件夹
        run: |
          # 注意：通过 -v 挂载，脚本会发现文件夹已存在，从而跳过 git clone 步骤
          docker run --rm \
            -v ${{ github.workspace }}/ol:/ol \
            -e username=${{ secrets.MY_USERNAME }} \
            -e token=${{ secrets.MY_GITHUB_TOKEN }} \
            -e url='https://www.iyouhun.com/tv/0,http://肥猫.com?&signame=肥猫' \
            -e repo=ol \
            -e mirror=0 \
            2011820123/tvbox:latest

      - name: 强制推送到当前仓库
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "TVBox_Bot"
          git add .
          # V1.7 逻辑：重置提交记录，防止仓库过大
          git commit --amend -m "Update TVBox Interface $(date +'%Y-%m-%d %H:%M')" || git commit -m "Update TVBox"
          git push --force
